name: ExtensionCore Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies
        working-directory: Project
        run: dotnet restore

      - name: Build
        working-directory: Project
        run: dotnet build --configuration Release --no-restore
      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: Project\ExtensionCore\bin\Release/
        
      - name: Test
        working-directory: Project
        run: dotnet test --no-restore --verbosity normal
    
    
